"""added column for user alerts aka notifications

Revision ID: 22dafe9d2000
Revises: 5983bb4dfef4
Create Date: 2023-04-23 23:01:38.440867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dafe9d2000'
down_revision = '5983bb4dfef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('alert')

    # ### end Alembic commands ###
