"""empty message

Revision ID: 369172df25f0
Revises: 81eb05d2affb
Create Date: 2023-03-03 18:47:27.612246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369172df25f0'
down_revision = '81eb05d2affb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)

    # ### end Alembic commands ###
