"""updating mode column

Revision ID: 6d1e819041b3
Revises: ff4dafa4610f
Create Date: 2023-02-18 20:44:27.303069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1e819041b3'
down_revision = 'ff4dafa4610f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('mode',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('mode',
               existing_type=sa.String(length=10),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
