"""updating alert column

Revision ID: 7d4751726c49
Revises: d472c520c4ad
Create Date: 2023-04-23 23:08:15.362866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4751726c49'
down_revision = 'd472c520c4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('alert',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('alert',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
