"""adding lots of new columns.

Revision ID: 7f655919ae04
Revises: 7d4751726c49
Create Date: 2023-06-01 12:33:37.279684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f655919ae04'
down_revision = '7d4751726c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('release_ended', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('release_weekly', sa.String(length=10000), nullable=True))
        batch_op.add_column(sa.Column('romajiTitle', sa.String(length=10000), nullable=True))
        batch_op.add_column(sa.Column('anilistId', sa.String(length=10000), nullable=True))
        batch_op.add_column(sa.Column('tvmazeId', sa.String(length=10000), nullable=True))
        batch_op.add_column(sa.Column('omdbId', sa.String(length=10000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('omdbId')
        batch_op.drop_column('tvmazeId')
        batch_op.drop_column('anilistId')
        batch_op.drop_column('romajiTitle')
        batch_op.drop_column('release_weekly')
        batch_op.drop_column('release_ended')
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###
