"""adding release status column in Card table for shows that are unreleased or currently releasing.

Revision ID: a7b40b772a1a
Revises: dfca85c76d66
Create Date: 2023-03-30 17:39:09.705347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b40b772a1a'
down_revision = 'dfca85c76d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_status', sa.String(length=10000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('release_status')

    # ### end Alembic commands ###
