"""added default for release_status to be released

Revision ID: c6361d5b9171
Revises: a7b40b772a1a
Create Date: 2023-03-30 17:48:13.988465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6361d5b9171'
down_revision = 'a7b40b772a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('release_status',
               existing_type=sa.VARCHAR(length=10000),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('release_status',
               existing_type=sa.VARCHAR(length=10000),
               nullable=True)

    # ### end Alembic commands ###
