"""added column for user alerts aka notifications

Revision ID: d472c520c4ad
Revises: 22dafe9d2000
Create Date: 2023-04-23 23:04:53.730363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd472c520c4ad'
down_revision = '22dafe9d2000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('alert')

    # ### end Alembic commands ###
